sonar.projectKey=Bhavik84_angular-demo
sonar.organization=bhavik84
sonar.projectName=Alabern
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/coverage/**,**/assets/**,src/*.xml

sonar.sourceEncoding=UTF-8
sonar.typescript.lcov.reportPaths=coverage/alabern/lcov.info
sonar.javascript.lcov.reportPaths=coverage/alabern/lcov.info
